# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxDemo
    pod 'RxSwift',    '~> 4.0'
    pod 'RxCocoa',    '~> 4.0'
    pod 'RxSwiftExt'
    pod 'Alamofire', '~> 4.7'
    pod 'ModelMapper'
    pod 'SDWebImage', '~> 4.0'
    pod 'RxDataSources', '~> 3.0'

  target 'RxDemoTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxBlocking', '~> 4.0'
    pod 'RxTest',     '~> 4.0'
  end

  target 'RxDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
